<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="7" hostname="DESKTOP-76QJ2J4" failures="1" tests="1" name="Default test" time="6.791" errors="0" timestamp="2025-03-14T22:45:31 IST">
  <testcase classname="testcases.TestLevelClass" name="verifyUserCanEnterEmptyName" time="0.186">
    <failure type="java.lang.AssertionError" message="Test failed: Entered Empty input value! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test failed: Entered Empty input value! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcases.TestLevelClass.verifyUserCanEnterEmptyName(TestLevelClass.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyUserCanEnterEmptyName -->
  <testcase classname="testcases.TestLevelClass" name="verifyTitleIsNotEmpty" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleIsNotEmpty -->
  <testcase classname="testcases.TestLevelClass" name="verifyUserCanEnterNameInNameInputBox" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUserCanEnterNameInNameInputBox -->
  <testcase classname="testcases.TestLevelClass" name="verifyIncorrectPageTitle" time="0.0">
    <ignored/>
  </testcase> <!-- verifyIncorrectPageTitle -->
  <testcase classname="testcases.TestLevelClass" name="verifyUserCannotEnterExcessivelyLongName" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUserCannotEnterExcessivelyLongName -->
  <testcase classname="testcases.TestLevelClass" name="verifyPageTitle" time="0.0">
    <ignored/>
  </testcase> <!-- verifyPageTitle -->
  <testcase classname="testcases.TestLevelClass" name="verifyUserCannotEnterSpecialCharacters" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUserCannotEnterSpecialCharacters -->
  <testcase classname="testcases.TestLevelClass" name="verifyTitleDoesNotContainUnexpectedText" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleDoesNotContainUnexpectedText -->
</testsuite> <!-- Default test -->
